/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/hw/AppFooter.vue')['default']
    HelloWorld: typeof import('./src/components/hw/HelloWorld.vue')['default']
    LinkTreeProfile: typeof import('./src/components/LinkTreeProfile.vue')['default']
    ProfilePage: typeof import('./src/components/ProfilePage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
